### ISSUE TITLE
insertion sort java

### ISSUE THREAD

**Issue by DurgaSanthosh** [ajitkumar1264/java-algorithms#138]

**Comment by priyansh2998** [comment]
InsertionSort.java is already there , can recheck

**Comment by BUNNY2210** [comment]
public static int[] ascendingInsertionSort(int[] array) {
    //Insertion sort in ascending order with for loop.
    for (int startingIndexToSort = 1; startingIndexToSort < array.length; startingIndexToSort++) {
        int valueAtStartingIndexToSort = array[startingIndexToSort];
        int i;
        for (i = startingIndexToSort; i >= 1 && valueAtStartingIndexToSort < array[i - 1]; i--) {
            array[i] = array[i - 1];
        }
        array[i] = valueAtStartingIndexToSort;
    }
    return array;
}
